# Generated by Django 5.0.7 on 2024-10-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=10)),
                ('EventDetails', models.CharField(max_length=50)),
                ('EventDate', models.DateField()),
                ('EventStatus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('StudName', models.CharField(max_length=25)),
                ('StudPhoneNo', models.CharField(max_length=12)),
                ('StudStatus', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('AttStatus', models.CharField(max_length=10)),
                ('EventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.event')),
                ('StudID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.student')),
            ],
        ),
    ]
