# Generated by Django 5.0.7 on 2024-10-13 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounting', '0004_remove_attendance_eventid_remove_attendance_studid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('StaffName', models.CharField(max_length=25)),
                ('StaffPass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('StudName', models.CharField(max_length=25)),
                ('StudPhoneNo', models.CharField(max_length=12)),
                ('StudPass', models.CharField(max_length=20)),
                ('StudStatus', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=10)),
                ('EventDetails', models.CharField(max_length=50)),
                ('EventDate', models.DateField()),
                ('EventTime', models.TimeField()),
                ('EventStatus', models.CharField(max_length=10)),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('FeedbackID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('EventRating', models.IntegerField()),
                ('Comment', models.CharField(max_length=100)),
                ('StudID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('AttStatus', models.CharField(max_length=10)),
                ('EventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.event')),
                ('StudID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.student')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('SuggestionID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Suggestion', models.CharField(max_length=100)),
                ('StudID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.student')),
            ],
        ),
    ]
