# Generated by Django 5.0.7 on 2024-10-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='StaffID',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='StudID',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='StudID',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
