# Generated by Django 5.0.7 on 2024-10-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0007_event_attendance_feedback_suggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
