# Generated by Django 5.0.7 on 2024-10-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0008_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('AttStatus', models.CharField(max_length=10)),
                ('EventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.event')),
                ('StudID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.student')),
            ],
        ),
    ]
