# Generated by Django 5.0.7 on 2024-10-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0009_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='Suggestion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='SuggestionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
