# Generated by Django 5.0.7 on 2024-10-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0010_alter_suggestion_suggestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='Suggestion',
            field=models.CharField(max_length=1000),
        ),
    ]
