# Generated by Django 5.0.7 on 2024-10-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0011_alter_suggestion_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='SuggestionID',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
