# Generated by Django 5.0.7 on 2024-10-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0012_alter_suggestion_suggestionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='Suggestion',
            new_name='Details',
        ),
    ]
